name: Build-$(Build.BuildId)

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    exclude:
    - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform version $(TF-Version)'
  inputs:
    terraformVersion: '$(TF-Version)'
- task: TerraformCLI@0
  displayName: 'Initialize'
  inputs:
    command: 'init'
- task: TerraformCLI@0
  displayName: 'Validate'
  inputs:
    command: 'validate'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: TerraformCLI@0
  displayName: 'Plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceName: 'Visual Studio Enterprise – MPN(3211b6f2-32a6-410d-97b9-5c24bcda7d0b)'
    commandOptions: '-var=location=$(location) -var=resource_group_name=$(resource-group)'
- task: TerraformCLI@0
  displayName: 'Apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceName: 'Visual Studio Enterprise – MPN(3211b6f2-32a6-410d-97b9-5c24bcda7d0b)'
    commandOptions: '-var=location=$(location) -var=resource_group_name=$(resource-group) -auto-approve'
- task: TerraformCLI@0
  displayName: 'Destroy'
  inputs:
    command: 'destroy'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceName: 'Visual Studio Enterprise – MPN(3211b6f2-32a6-410d-97b9-5c24bcda7d0b)'
    commandOptions: '-var=location=$(location) -var=resource_group_name=$(resource-group) -auto-approve'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/*
     !.git/**/*
     !.terraform/**/*
     !*.tfstate
     !*.tfstate.*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_jungopro'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Notes'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'